site_name: NetBox文档
site_dir: netbox/project-static/docs
site_url: https://docs.netbox.dev/
repo_name: netbox-community/netbox
repo_url: https://github.com/netbox-community/netbox
theme:
  name: material
  custom_dir: docs/_theme/
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: 切换到浅色模式
plugins:
  - search:
      lang: zh
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.chdir('netbox/')
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "netbox.settings")
            - django.setup()
          options:
            heading_level: 3
            members_order: source
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zituoguan/netbox
    - icon: fontawesome/brands/slack
      link: https://netdev.chat/
extra_css:
    - extra.css
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
nav:
    - 介绍: 'introduction.md'
    - 特性:
        - 设施: 'features/facilities.md'
        - 设备与布线: 'features/devices-cabling.md'
        - 电源跟踪: 'features/power-tracking.md'
        - IPAM: 'features/ipam.md'
        - VLAN管理: 'features/vlan-management.md'
        - L2VPN与覆盖: 'features/l2vpn-overlay.md'
        - 电路: 'features/circuits.md'
        - 无线: 'features/wireless.md'
        - 虚拟化: 'features/virtualization.md'
        - VPN隧道: 'features/vpn-tunnels.md'
        - 租户: 'features/tenancy.md'
        - 联系人: 'features/contacts.md'
        - 搜索: 'features/search.md'
        - 上下文数据: 'features/context-data.md'
        - 配置渲染: 'features/configuration-rendering.md'
        - 同步数据: 'features/synchronized-data.md'
        - 变更日志: 'features/change-logging.md'
        - 日志记录: 'features/journaling.md'
        - 事件规则: 'features/event-rules.md'
        - 后台作业: 'features/background-jobs.md'
        - 认证与权限: 'features/authentication-permissions.md'
        - API与集成: 'features/api-integration.md'
        - 定制: 'features/customization.md'
    - 安装与升级:
        - 安装NetBox: 'installation/index.md'
        - 1. PostgreSQL: 'installation/1-postgresql.md'
        - 2. Redis: 'installation/2-redis.md'
        - 3. NetBox: 'installation/3-netbox.md'
        - 4. Gunicorn: 'installation/4-gunicorn.md'
        - 5. HTTP服务器: 'installation/5-http-server.md'
        - 6. LDAP（可选）: 'installation/6-ldap.md'
        - 升级NetBox: 'installation/upgrading.md'
    - 入门指南:
        - 计划: 'getting-started/planning.md'
        - 填充数据: 'getting-started/populating-data.md'
    - 配置:
        - 配置NetBox: 'configuration/index.md'
        - 必需参数: 'configuration/required-parameters.md'
        - 系统: 'configuration/system.md'
        - 安全性: 'configuration/security.md'
        - 远程认证: 'configuration/remote-authentication.md'
        - 数据与验证: 'configuration/data-validation.md'
        - 默认值: 'configuration/default-values.md'
        - 错误报告: 'configuration/error-reporting.md'
        - 插件: 'configuration/plugins.md'
        - 日期与时间: 'configuration/date-time.md'
        - 杂项: 'configuration/miscellaneous.md'
        - 开发: 'configuration/development.md'
    - 定制:
        - 自定义字段: 'customization/custom-fields.md'
        - 自定义链接: 'customization/custom-links.md'
        - 自定义验证: 'customization/custom-validation.md'
        - 导出模板: 'customization/export-templates.md'
        - 报告: 'customization/reports.md'
        - 自定义脚本: 'customization/custom-scripts.md'
    - 集成:
        - REST API: 'integrations/rest-api.md'
        - GraphQL API: 'integrations/graphql-api.md'
        - Webhooks: 'integrations/webhooks.md'
        - 同步数据: 'integrations/synchronized-data.md'
        - Prometheus指标: 'integrations/prometheus-metrics.md'
    - 插件:
        - 使用插件: 'plugins/index.md'
        - 开发插件:
            - 入门: 'plugins/development/index.md'
            - 模型: 'plugins/development/models.md'
            - 视图: 'plugins/development/views.md'
            - 导航: 'plugins/development/navigation.md'
            - 模板: 'plugins/development/templates.md'
            - 表格: 'plugins/development/tables.md'
            - 表单: 'plugins/development/forms.md'
            - 过滤器与过滤器集: 'plugins/development/filtersets.md'
            - 搜索: 'plugins/development/search.md'
            - 数据后端: 'plugins/development/data-backends.md'
            - REST API: 'plugins/development/rest-api.md'
            - GraphQL API: 'plugins/development/graphql-api.md'
            - 后台任务: 'plugins/development/background-tasks.md'
            - 仪表板小部件: 'plugins/development/dashboard-widgets.md'
            - 暂存更改: 'plugins/development/staged-changes.md'
            - 异常: 'plugins/development/exceptions.md'
    - 管理:
        - 认证:
            - 概述: 'administration/authentication/overview.md'
            - Microsoft Azure AD: 'administration/authentication/microsoft-azure-ad.md'
            - Okta: 'administration/authentication/okta.md'
        - 权限: 'administration/permissions.md'
        - 错误报告: 'administration/error-reporting.md'
        - 清理: 'administration/housekeeping.md'
        - 复制NetBox: 'administration/replicating-netbox.md'
        - NetBox Shell: 'administration/netbox-shell.md'
    - 数据模型:
        - 电路:
            - 电路: 'models/circuits/circuit.md'
            - 电路终止: 'models/circuits/circuittermination.md'
            - 电路类型: 'models/circuits/circuittype.md'
            - 提供商: 'models/circuits/provider.md'
            - 提供商账户: 'models/circuits/provideraccount.md'
            - 提供商网络: 'models/circuits/providernetwork.md'
        - 核心:
            - 数据文件: 'models/core/datafile.md'
            - 数据源: 'models/core/datasource.md'
            - 任务: 'models/core/job.md'
        - DCIM:
            - 电缆: 'models/dcim/cable.md'
            - 控制台端口: 'models/dcim/consoleport.md'
            - 控制台端口模板: 'models/dcim/consoleporttemplate.md'
            - 控制台服务器端口: 'models/dcim/consoleserverport.md'
            - 控制台服务器端口模板: 'models/dcim/consoleserverporttemplate.md'
            - 设备: 'models/dcim/device.md'
            - 设备托架: 'models/dcim/devicebay.md'
            - 设备托架模板: 'models/dcim/devicebaytemplate.md'
            - 设备角色: 'models/dcim/devicerole.md'
            - 设备类型: 'models/dcim/devicetype.md'
            - 正面端口: 'models/dcim/frontport.md'
            - 正面端口模板: 'models/dcim/frontporttemplate.md'
            - 接口: 'models/dcim/interface.md'
            - 接口模板: 'models/dcim/interfacetemplate.md'
            - 库存项: 'models/dcim/inventoryitem.md'
            - 库存项角色: 'models/dcim/inventoryitemrole.md'
            - 库存项模板: 'models/dcim/inventoryitemtemplate.md'
            - 位置: 'models/dcim/location.md'
            - 制造商: 'models/dcim/manufacturer.md'
            - 模块: 'models/dcim/module.md'
            - 模块托架: 'models/dcim/modulebay.md'
            - 模块托架模板: 'models/dcim/modulebaytemplate.md'
            - 模块类型: 'models/dcim/moduletype.md'
            - 平台: 'models/dcim/platform.md'
            - 电源馈线: 'models/dcim/powerfeed.md'
            - 电源插座: 'models/dcim/poweroutlet.md'
            - 电源插座模板: 'models/dcim/poweroutlettemplate.md'
            - 电源面板: 'models/dcim/powerpanel.md'
            - 电源端口: 'models/dcim/powerport.md'
            - 电源端口模板: 'models/dcim/powerporttemplate.md'
            - 机架: 'models/dcim/rack.md'
            - 机架预约: 'models/dcim/rackreservation.md'
            - 机架角色: 'models/dcim/rackrole.md'
            - 后置端口: 'models/dcim/rearport.md'
            - 后置端口模板: 'models/dcim/rearporttemplate.md'
            - 区域: 'models/dcim/region.md'
            - 站点: 'models/dcim/site.md'
            - 站点组: 'models/dcim/sitegroup.md'
            - 虚拟机箱: 'models/dcim/virtualchassis.md'
            - 虚拟设备上下文: 'models/dcim/virtualdevicecontext.md'
        - 附加组件:
            - 书签: 'models/extras/bookmark.md'
            - 分支: 'models/extras/branch.md'
            - 配置上下文: 'models/extras/configcontext.md'
            - 配置模板: 'models/extras/configtemplate.md'
            - 自定义字段: 'models/extras/customfield.md'
            - 自定义字段选择集: 'models/extras/customfieldchoiceset.md'
            - 自定义链接: 'models/extras/customlink.md'
            - 事件规则: 'models/extras/eventrule.md'
            - 导出模板: 'models/extras/exporttemplate.md'
            - 图像附件: 'models/extras/imageattachment.md'
            - 日志条目: 'models/extras/journalentry.md'
            - 已保存的过滤器: 'models/extras/savedfilter.md'
            - 暂存更改: 'models/extras/stagedchange.md'
            - 标签: 'models/extras/tag.md'
            - Webhook: 'models/extras/webhook.md'
        - IPAM:
            - ASN: 'models/ipam/asn.md'
            - ASN范围: 'models/ipam/asnrange.md'
            - 聚合: 'models/ipam/aggregate.md'
            - FHRP组: 'models/ipam/fhrpgroup.md'
            - FHRP组分配: 'models/ipam/fhrpgroupassignment.md'
            - IP地址: 'models/ipam/ipaddress.md'
            - IP范围: 'models/ipam/iprange.md'
            - 前缀: 'models/ipam/prefix.md'
            - RIR: 'models/ipam/rir.md'
            - 角色: 'models/ipam/role.md'
            - 路由目标: 'models/ipam/routetarget.md'
            - 服务: 'models/ipam/service.md'
            - 服务模板: 'models/ipam/servicetemplate.md'
            - VLAN: 'models/ipam/vlan.md'
            - VLAN组: 'models/ipam/vlangroup.md'
            - VRF: 'models/ipam/vrf.md'
        - 租户:
            - 联系人: 'models/tenancy/contact.md'
            - 联系人组: 'models/tenancy/contactgroup.md'
            - 联系人角色: 'models/tenancy/contactrole.md'
            - 租户: 'models/tenancy/tenant.md'
            - 租户组: 'models/tenancy/tenantgroup.md'
        - 虚拟化:
            - 群集: 'models/virtualization/cluster.md'
            - 群集组: 'models/virtualization/clustergroup.md'
            - 群集类型: 'models/virtualization/clustertype.md'
            - VM接口: 'models/virtualization/vminterface.md'
            - 虚拟磁盘: 'models/virtualization/virtualdisk.md'
            - 虚拟机: 'models/virtualization/virtualmachine.md'
        - VPN:
            - IKE策略: 'models/vpn/ikepolicy.md'
            - IKE提案: 'models/vpn/ikeproposal.md'
            - IPSec策略: 'models/vpn/ipsecpolicy.md'
            - IPSec配置文件: 'models/vpn/ipsecprofile.md'
            - IPSec提案: 'models/vpn/ipsecproposal.md'
            - L2VPN: 'models/vpn/l2vpn.md'
            - L2VPN终止: 'models/vpn/l2vpntermination.md'
            - 隧道: 'models/vpn/tunnel.md'
            - 隧道组: 'models/vpn/tunnelgroup.md'
            - 隧道终止: 'models/vpn/tunneltermination.md'
        - 无线:
            - 无线局域网: 'models/wireless/wirelesslan.md'
            - 无线局域网组: 'models/wireless/wirelesslangroup.md'
            - 无线链接: 'models/wireless/wirelesslink.md'
    - 参考:
        - 过滤: 'reference/filtering.md'
        - 条件: 'reference/conditions.md'
        - Markdown: 'reference/markdown.md'
    - 开发:
        - 介绍: 'development/index.md'
        - 入门指南: 'development/getting-started.md'
        - 样式指南: 'development/style-guide.md'
        - 模型: 'development/models.md'
        - 添加模型: 'development/adding-models.md'
        - 扩展模型: 'development/extending-models.md'
        - 信号: 'development/signals.md'
        - 搜索: 'development/search.md'
        - 应用注册表: 'development/application-registry.md'
        - 用户首选项: 'development/user-preferences.md'
        - Web界面: 'development/web-ui.md'
        - 国际化: 'development/internationalization.md'
        - 发布检查列表: 'development/release-checklist.md'
        - git Cheat Sheet: 'development/git-cheat-sheet.md'
    - 发布说明:
        - 概述: 'release-notes/index.md'
        - 版本 3.7: 'release-notes/version-3.7.md'
        - 版本 3.6: 'release-notes/version-3.6.md'
        - 版本 3.5: 'release-notes/version-3.5.md'
        - 版本 3.4: 'release-notes/version-3.4.md'
        - 版本 3.3: 'release-notes/version-3.3.md'
        - 版本 3.2: 'release-notes/version-3.2.md'
        - 版本 3.1: 'release-notes/version-3.1.md'
        - 版本 3.0: 'release-notes/version-3.0.md'
        - 版本 2.11: 'release-notes/version-2.11.md'
        - 版本 2.10: 'release-notes/version-2.10.md'
        - 版本 2.9: 'release-notes/version-2.9.md'
        - 版本 2.8: 'release-notes/version-2.8.md'
        - 版本 2.7: 'release-notes/version-2.7.md'
        - 版本 2.6: 'release-notes/version-2.6.md'
        - 版本 2.5: 'release-notes/version-2.5.md'
        - 版本 2.4: 'release-notes/version-2.4.md'
        - 版本 2.3: 'release-notes/version-2.3.md'
        - 版本 2.2: 'release-notes/version-2.2.md'
        - 版本 2.1: 'release-notes/version-2.1.md'
        - 版本 2.0: 'release-notes/version-2.0.md'

